#!/bin/sh
PATH="/usr/X11R6/bin:/usr/bin:/bin:/sbin:/usr/sbin"
export PATH

KDELOCK=/usr/bin/kdesktop_lock.orig

[ -x "$KDELOCK" ] || exit 0

if [ "`id -un`" = "knoppix" ]; then
# reconstruct commandline
OPTIONS=""
for i in "$@"; do
[ "$i" = "--forcelock" ] && i="--dontlock"
OPTIONS="$OPTIONS $i"
done
exec /usr/bin/kdesktop_lock.orig $OPTIONS
else
exec /usr/bin/kdesktop_lock.orig "$@"
fi
